### ISSUE TITLE
Error Code 500

### ISSUE THREAD

**Issue by ElegantPercentage** [parker-stephens/siriusxm-activator#3]
`{"faultcode":"10001","faultdetail":"Authorization Failed","opstatus":8005,"errmsg":"Not Authorized","httpStatusCode":500}`

When I click `Create an account for your radio.` Getting back an error code of 500 on the console response. I have CORS disabled.

**Comment by akadeno** [comment]
Maybe their systems were down? I just ran it on a few radios successfully. I also found I had to run brave by running:   brave.exe --user-data-dir="C://Chrome dev session" --disable-web-security "<directory you stored the files>\index.html"

Then I was successful each time. Hope this helps.

**Comment by Drivium** [comment]
I don't get any indication this is working. I ran with brave and flags as mentioned above, but the buttons "Create an account" and "Activate" don't give any indication they've done anything. Does this still work?
