### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by NikoV5** [parker-stephens/siriusxm-activator#5]
Does this not work anymore? I'm not getting any error messages or anything but I can't seem to get it to work on cars that is has always worked on.

**Comment by elliottl07** [comment]
No it stopped working months ago

**Comment by mustang5269** [comment]
I haven't had any luck last couple tries.

**Comment by parker-stephens** [comment]
#4 has an alternate solution to activating a radio that is much better than this was. See the following comment. https://github.com/parker-stephens/siriusxm-activator/issues/4#issuecomment-1355609583
