### ISSUE TITLE
Radio account creation problem

### ISSUE THREAD

**Issue by apexiptv** [parker-stephens/siriusxm-activator#6]
I put the radio ID in, hit create account, then activate radio, this is what comes out over in the console.. Not sure why as it is an inactive radio for over a month now. The script worked on my rental car just a few weeks ago.

{"opstatus":0,"seqValue":"11478522","errors":[{"resultCode":"FAILURE"},{"code":"11-09-SMSP-1185"},{"message":"Old Device not associated to an account"}],"httpStatusCode":200}

![image](https://user-images.githubusercontent.com/42727116/210465245-e5de11c9-e700-4e0c-be37-d16ce6100ec7.png)

**Comment by parker-stephens** [comment]
Hi, please see https://github.com/parker-stephens/siriusxm-activator/issues/4#issuecomment-1356483271.
