### ISSUE TITLE
replit Link only opens read me

### ISSUE THREAD

**Issue by hewsty** [parker-stephens/siriusxm-activator#8]
When clicking the link on iPhone to take me to the replit page it only opens the read me file.

**Comment by hewsty** [comment]
Is there a step I'm missing I was able to use this on my iPhone 2weeks ago but now the link just takes me to the read me

**Comment by parker-stephens** [comment]
You have to fork it to your own account. 

[](https://blog.replit.com/hosting-changes)

**Comment by hewsty** [comment]
Thank you will do!!
